---
apiVersion: v1
kind: Secret
metadata:
  name: s3-keys
  namespace: azul-app
type: Opaque
data:
  accesskey: YXp1bG1pbmlv
  secretkey: aUE0Tk00SllzZlNCbkxSSDFiZ2htYTRabGhWZEwxbjZOWnFjMENmbkRWNkhWWjMz
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-keys
  namespace: azul-app
type: Opaque
data:
  access_key: YXp1bGJhY2t1cA==
  secret_key: Z3JzL0VNVUhwZ3c3eWxiSnR1M0NabDlPSFhaL0xFdm90YlZYaG5QSDBrd1BSU21U
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: azul-app
type: Opaque
data:
  redis-password: cjZOU09MbXhDY0loSFJNZnlXbWR1cFpaa0d6M1dPUXIzOXFhV1FyNDc1N1VHYis1
  redis-username: ZGVmYXVsdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: metastore-creds
  namespace: azul-app
type: Opaque
data:
  jwt_signing_secret: REJzSjhZb0hYYXdSRllKdkwrNEY2dkNEMXZBZ1kvWGNHOEVQcTI1Z29hbEtnbkprOWFIWWFYQnZoZ3ZLYXIwbw==
  opensearch_azul_security_password: YWRtaW5wYXNzd29yZA==
  writer: YWRtaW5wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: azul-service-account
  namespace: azul-app
type: Opaque
data:
  client_id: YXp1bC1zZXJ2aWNl
  client_secret: SU1PRTNZRWZMZGEyRlg5M1kxamlxWnNKZHFJc3RRMEM=
